### ISSUE TITLE
 instruction "go get github.com/layeh/gopus" wrong?

### ISSUE THREAD

**Issue by tommyhlw** [MarcusWolschon/RasPi_stage_intercom#6]
got some trouble to build the file because of gopus
with "go get github.com/dchote/gopus" i could do it

**Comment by MarcusWolschon** [comment]
No error message?
This is code from the TalkiPi project we cloned from. 
Since I'm not a Go developer, it would be best to ask there.

**Comment by MarcusWolschon** [comment]
fixed.
