### ISSUE TITLE
babyphone mode

### ISSUE THREAD

**Issue by tommyhlw** [MarcusWolschon/RasPi_stage_intercom#7]
I'd like to modify the talkiepi as a babyphone with voice activation. Therefore no GPIO LEDs and buttons are required. 

As far I understood "client.go" and "talkiepi.go" needs to be modified in a way that no "gpio.go" are needed and the button function needs to be replaced by the voice activation.

Could you give me a hint how I could realize this mod? Or is it a simple adjustment of configs?

**Comment by MarcusWolschon** [comment]
That doesn't make much sense.
You could use the default client. (https://github.com/layeh/barnard)
